In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing

from sklearn.preprocessing import LabelEncoder

df = pd.read_csv("../dataSets/Time management data.csv")
df.head()
df.columns[20]

'17'

In [2]:
option_scores6 = {
    'Strong Agree': 1,
    'Agree': 2,
    'Neither': 3,
    'Disagree': 4,
    'Strong Disagree': 5
}

option_scores7 = {
    'Strong Agree': 5,
    'Agree': 4,
    'Neither': 3,
    'Disagree': 2,
    'Strong Disagree': 1
}


option_scores8 = {
    'Strong Agree': 5,
    'Agree': 4,
    'Neither': 3,
    'Disagree': 2,
    'Strong Disagree': 1
}


option_scores9 = {
    'Strong Agree': 1,
    'Agree': 2,
    'Neither': 3,
    'Disagree': 4,
    'Strong Disagree': 5
}


option_scores10 = {
    'Strong Agree': 5,
    'Agree': 4,
    'Neither': 3,
    'Disagree': 2,
    'Strong Disagree': 1
}

option_scores11 = {
    'Strong Agree': 1,
    'Agree': 2,
    'Neither': 3,
    'Disagree': 4,
    'Strong Disagree': 5
}

option_scores12 = {
    'Strong Agree': 1,
    'Agree': 2,
    'Neither': 3,
    'Disagree': 4,
    'Strong Disagree': 5
}
option_scores13 = {
    'Strong Agree': 1,
    'Agree': 2,
    'Neither': 3,
    'Disagree': 4,
    'Strong Disagree': 5
}


option_scores14 = {
    'Strong Agree': 5,
    'Agree': 4,
    'Neither': 3,
    'Disagree': 2,
    'Strong Disagree': 1
}

option_scores15 = {
    'Strong Agree': 1,
    'Agree': 2,
    'Neither': 3,
    'Disagree': 4,
    'Strong Disagree': 5
}

option_scores16 = {
    'Strong Agree': 1,
    'Agree': 2,
    'Neither': 3,
    'Disagree': 4,
    'Strong Disagree': 5
}

option_scores17 = {
    'Strong Agree': 5,
    'Agree': 4,
    'Neither': 3,
    'Disagree': 2,
    'Strong Disagree': 1
}

In [3]:
columns_to_sum = df.columns[9:21]
print(columns_to_sum)

Index(['6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17'], dtype='object')

In [4]:
column_score_mapping = {
    '6': option_scores6,
    '7': option_scores7, 
    '8': option_scores8,
    '9': option_scores9,
    '10': option_scores10,
    '11': option_scores11,
    '12': option_scores12,
    '13': option_scores13,
    '14': option_scores14,
    '15': option_scores15,
    '16': option_scores16,
    '17': option_scores17,# Replace with the actual name of your dictionary for Column7
    # Repeat for other columns
}

# Iterate through each column and apply the corresponding scores
for column in columns_to_sum:
    df[column] = df[column].map(column_score_mapping[column])

# Sum the scores for each row
df['Total_Score'] = df[columns_to_sum].sum(axis=1)

# Display the DataFrame with the total scores
print(df[['Total_Score']])

     Total_Score
0           48.0
1           38.0
2           38.0
3           36.0
4           36.0
..           ...
120         37.0
121         26.0
122         38.0
123         27.0
124         45.0

[125 rows x 1 columns]

In [5]:
csv_file_path = "../dataSets/tmp.csv"
df.to_csv(csv_file_path,index=False)

In [6]:
conditions = [
    (df['Total_Score'] >= 45),
    (df['Total_Score'] >= 35) & (df['Total_Score'] < 45),
    (df['Total_Score'] >= 25) & (df['Total_Score'] < 35),
]

choices = ['45+', '35-45', '25-35']
df['Score Range'] = np.select(conditions, choices, default='Other')

In [7]:
csv_file_path = "../dataSets/tmp.csv"
df.to_csv(csv_file_path,index=False)

In [8]:
df.columns

Index(['Number', 'Age', 'Gender', 'Nationality', 'Program', 'Course',
       'English', 'Academic', 'Attendance', '6', '7', '8', '9', '10', '11',
       '12', '13', '14', '15', '16', '17', 'Scores', 'Score Range',
       'Total_Score'],
      dtype='object')

In [9]:
option_scores6 = {
    1.0:'Strong Agree',
    2.0:'Agree',
    3:'Neither',
    4:'Disagree',
    5:'Strong Disagree'
}
option_scores7 = {
    5:'Strong Agree',
    4:'Agree',
    3:'Neither',
    2:'Disagree',
    1:'Strong Disagree'
}
option_scores8 = {
    5:'Strong Agree',
    4:'Agree',
    3:'Neither',
    2:'Disagree',
    1:'Strong Disagree'
}

option_scores9 = {
    1:'Strong Agree',
    2:'Agree',
    3:'Neither',
    4:'Disagree',
    5:'Strong Disagree'
}
option_scores10 = {
    5:'Strong Agree',
    4:'Agree',
    3:'Neither',
    2:'Disagree',
    1:'Strong Disagree'
}

option_scores11 = {
    1:'Strong Agree',
    2:'Agree',
    3:'Neither',
    4:'Disagree',
    5:'Strong Disagree'
}

option_scores12 = {
    1:'Strong Agree',
    2:'Agree',
    3:'Neither',
    4:'Disagree',
    5:'Strong Disagree'
}
option_scores13 = {
    1:'Strong Agree',
    2:'Agree',
    3:'Neither',
    4:'Disagree',
    5:'Strong Disagree'
}
option_scores14 = {
    5:'Strong Agree',
    4:'Agree',
    3:'Neither',
    2:'Disagree',
    1:'Strong Disagree'
}

option_scores15 = {
    1:'Strong Agree',
    2:'Agree',
    3:'Neither',
    4:'Disagree',
    5:'Strong Disagree'
}

option_scores16 = {
    1:'Strong Agree',
    2:'Agree',
    3:'Neither',
    4:'Disagree',
    5:'Strong Disagree'
}
option_scores17 = {
    5:'Strong Agree',
    4:'Agree',
    3:'Neither',
    2:'Disagree',
    1:'Strong Disagree'
}

In [10]:
column_score_mapping = {
    '6': option_scores6,
    '7': option_scores7, 
    '8': option_scores8,
    '9': option_scores9,
    '10': option_scores10,
    '11': option_scores11,
    '12': option_scores12,
    '13': option_scores13,
    '14': option_scores14,
    '15': option_scores15,
    '16': option_scores16,
    '17': option_scores17,# Replace with the actual name of your dictionary for Column7
    # Repeat for other columns
}
for column in columns_to_sum:
    df[column] = df[column].map(column_score_mapping[column])

In [11]:
df.head()

,Number,Age,Gender,Nationality,Program,Course,English,Academic,Attendance,6,...,11,12,13,14,15,16,17,Scores,Score Range,Total_Score
0,1,31-35,M,Korea,PM,Social Sciences and Humanities,60%~70%,NaN,S0,Disagree,...,Neither,Disagree,Strong Disagree,Strong Agree,Neither,Disagree,Agree,48.0,45+,48.0
1,2,26-30,M,China,PM,Science and engineering,60%~70%,50%~59%,S3,Strong Agree,...,Neither,Disagree,Strong Disagree,Neither,Agree,Neither,Disagree,42.0,35-45,38.0
2,3,26-30,M,Kenya,PM,Business,60%~70%,NaN,S0,Disagree,...,Agree,Disagree,Strong Disagree,Disagree,Strong Agree,Strong Agree,Disagree,38.0,35-45,38.0
3,4,21-25,M,Vietnam,PM,Law/Legal studies,60%~70%,60%~70%,S0,Disagree,...,Agree,Neither,Neither,Neither,Neither,Disagree,Agree,36.0,35-45,36.0
4,5,21-25,M,China,PM,Business,60%~70%,50%~59%,S1,Neither,...,Neither,Neither,Neither,Neither,Disagree,Neither,Agree,34.0,35-45,36.0

In [12]:
df.info

<bound method DataFrame.info of      Number    Age Gender Nationality Program                          Course  \
0         1  31-35      M       Korea      PM  Social Sciences and Humanities
1         2  26-30      M       China      PM         Science and engineering
2         3  26-30      M       Kenya      PM                        Business
3         4  21-25      M     Vietnam      PM               Law/Legal studies
4         5  21-25      M       China      PM                        Business
..      ...    ...    ...         ...     ...                             ...
120     121  21-25      M       China      PM                        Business
121     122  31-35      F       China      PM                        Business
122     123  26-30      M       Gongo      PM                        Business
123     124  21-25      F     Ukraine      PM                        Business
124     125  26-30      F       Korea      PM                        Business

     English Academic Attendance                6  ...               11  \
0    60%~70%      NaN         S0         Disagree  ...          Neither
1    60%~70%  50%~59%         S3     Strong Agree  ...          Neither
2    60%~70%      NaN         S0         Disagree  ...            Agree
3    60%~70%  60%~70%         S0         Disagree  ...            Agree
4    60%~70%  50%~59%         S1          Neither  ...          Neither
..       ...      ...        ...              ...  ...              ...
120  60%~70%  50%~59%         S1         Disagree  ...         Disagree
121  50%~59%  50%~59%         S1            Agree  ...     Strong Agree
122     >70%  60%~70%         S0  Strong Disagree  ...          Neither
123  60%~70%  60%~70%         S1            Agree  ...            Agree
124  60%~70%     >70%         S0         Disagree  ...  Strong Disagree

           12               13            14            15            16  \
0    Disagree  Strong Disagree  Strong Agree       Neither      Disagree
1    Disagree  Strong Disagree       Neither         Agree       Neither
2    Disagree  Strong Disagree      Disagree  Strong Agree  Strong Agree
3     Neither          Neither       Neither       Neither      Disagree
4     Neither          Neither       Neither      Disagree       Neither
..        ...              ...           ...           ...           ...
120   Neither         Disagree      Disagree         Agree       Neither
121     Agree            Agree      Disagree         Agree  Strong Agree
122   Neither  Strong Disagree      Disagree  Strong Agree      Disagree
123     Agree  Strong Disagree      Disagree  Strong Agree      Disagree
124  Disagree  Strong Disagree         Agree       Neither      Disagree

               17 Scores Score Range Total_Score
0           Agree   48.0         45+        48.0
1        Disagree   42.0       35-45        38.0
2        Disagree   38.0       35-45        38.0
3           Agree   36.0       35-45        36.0
4           Agree   34.0       35-45        36.0
..            ...    ...         ...         ...
120         Agree   37.0       35-45        37.0
121         Agree   26.0       25-35        26.0
122       Neither   38.0       35-45        38.0
123      Disagree   27.0       25-35        27.0
124  Strong Agree   45.0         45+        45.0

[125 rows x 24 columns]>